"""SSE answer composition: OpenAI Responses (preferred), Gemini fallback, demo extractive.

Yields the contract's event dicts — ``delta`` … ``citations`` ``done`` — with
errors mid-stream surfaced as a final ``error`` event.
"""

from collections.abc import Iterator
from typing import Any

import openai
from google import genai
from google.genai import errors, types

from docsage_api.core.config import Settings
from docsage_api.services.retrieval import RetrievedChunk
from docsage_api.services.retry import call_with_retries

_RETRYABLE_HTTP = {408, 429, 500, 502, 503, 504}
_HTTP_TIMEOUT_S = 60.0
DEMO_EXCERPT_CHARS = 220
DEMO_EXCERPTS = 3
SNIPPET_CHARS = 200

# Stable grounding instructions come BEFORE dynamic content (prompt-cache guidance).
STABLE_GROUNDING_INSTRUCTIONS = """You are DocSage, an agency knowledge assistant.
Answer ONLY from the numbered <sources> passages provided.
- Cite every claim inline with [n] markers matching the passage numbers.
- If the sources do not answer the question, say so plainly; never invent policy.
- Be concise and factual; no preamble beyond the answer itself."""


def _gemini_retryable(exc: Exception) -> bool:
    return isinstance(exc, errors.APIError) and exc.code in _RETRYABLE_HTTP


def _openai_retryable(exc: Exception) -> bool:
    return isinstance(exc, openai.APIStatusError) and exc.status_code in _RETRYABLE_HTTP


def _sources_block(retrieved: list[RetrievedChunk]) -> str:
    lines = []
    for i, chunk in enumerate(retrieved, start=1):
        location = f" (page {chunk.page})" if chunk.page is not None else ""
        body = " ".join(chunk.content.split())
        lines.append(f"[{i}] {chunk.document_title}{location}: {body}")
    return "\n".join(lines)


def build_citations(retrieved: list[RetrievedChunk]) -> list[dict[str, Any]]:
    """Citation dicts in [n] order (the order the answer prompt numbers them by)."""
    citations = []
    for chunk in retrieved:
        snippet = " ".join(chunk.content.split())
        citations.append(
            {
                "chunk_id": str(chunk.chunk_id),
                "document_id": str(chunk.document_id),
                "document_title": chunk.document_title,
                "snippet": snippet[:SNIPPET_CHARS],
                "score": round(chunk.similarity, 4),
                **({"page": chunk.page} if chunk.page is not None else {}),
            }
        )
    return citations


class AnswerService:
    """Streams one grounded answer for a question over retrieved passages."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._openai: openai.OpenAI | None = None
        self._gemini: genai.Client | None = None

    def stream(
        self, question: str, retrieved: list[RetrievedChunk], message_id: str
    ) -> Iterator[dict[str, Any]]:
        """Emit delta events for the answer, then citations and done/message_id.

        ``message_id`` is pre-generated by the caller (the chat router), which
        persists the assistant message with that id once the stream completes.
        Failures surface as a final ``error`` event — no citations, no done.
        """
        try:
            if self._settings.openai_enabled:
                deltas = self._stream_openai(question, retrieved)
            elif self._settings.gemini_enabled:
                deltas = self._stream_gemini(question, retrieved)
            else:
                deltas = self._stream_demo(question, retrieved)
            for delta in deltas:
                yield {"type": "delta", "text": delta}
        except Exception as exc:
            yield {"type": "error", "message": f"answer generation failed: {exc}"}
            return
        yield {"type": "citations", "citations": build_citations(retrieved)}
        yield {"type": "done", "message_id": message_id}

    # ------------------------------------------------------------- openai

    def _openai_client(self) -> openai.OpenAI:
        if self._openai is None:
            self._openai = openai.OpenAI(
                api_key=self._settings.openai_api_key or None,
                base_url=self._settings.openai_base_url or None,
                timeout=_HTTP_TIMEOUT_S,
            )
        return self._openai

    def _stream_openai(self, question: str, retrieved: list[RetrievedChunk]) -> Iterator[str]:
        client = self._openai_client()
        stream = call_with_retries(
            lambda: client.responses.create(
                model=self._settings.openai_chat_model,
                instructions=STABLE_GROUNDING_INSTRUCTIONS,
                input=(
                    f"<sources>\n{_sources_block(retrieved)}\n</sources>\n\nQuestion: {question}"
                    if retrieved
                    else (
                        f"{STABLE_GROUNDING_INSTRUCTIONS}\n\n"
                        "No sources were retrieved. State that no documentation "
                        f"answers this question.\n\nQuestion: {question}"
                    )
                ),
                stream=True,
            ),
            is_retryable=_openai_retryable,
        )
        for event in stream:
            if getattr(event, "type", "") == "response.output_text.delta":
                yield event.delta

    # ------------------------------------------------------------- gemini

    def _gemini_client(self) -> genai.Client:
        if self._gemini is None:
            self._gemini = genai.Client(
                api_key=self._settings.gemini_api_key,
                http_options=types.HttpOptions(timeout=_HTTP_TIMEOUT_S * 1000),
            )
        return self._gemini

    def _stream_gemini(self, question: str, retrieved: list[RetrievedChunk]) -> Iterator[str]:
        client = self._gemini_client()
        if retrieved:
            prompt = f"<sources>\n{_sources_block(retrieved)}\n</sources>\n\nQuestion: {question}"
        else:
            prompt = (
                "No sources were retrieved. State that no documentation answers "
                f"this question.\n\nQuestion: {question}"
            )
        stream = call_with_retries(
            lambda: client.models.generate_content_stream(
                model=self._settings.gemini_vision_model,
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=STABLE_GROUNDING_INSTRUCTIONS
                ),
            ),
            is_retryable=_gemini_retryable,
        )
        for chunk in stream:
            if chunk.text:
                yield chunk.text

    # --------------------------------------------------------------- demo

    def _stream_demo(self, question: str, retrieved: list[RetrievedChunk]) -> Iterator[str]:
        yield (
            f"Demo mode — extractive answer from {len(retrieved)} retrieved passage"
            f"{'s' if len(retrieved) != 1 else ''}. No language model is configured; "
            "the excerpts below are the top retrieved passages, clearly labeled.\n\n"
        )
        if not retrieved:
            yield f"No passages were retrieved for: {question}"
            return
        for i, chunk in enumerate(retrieved[:DEMO_EXCERPTS], start=1):
            excerpt = " ".join(chunk.content.split())[:DEMO_EXCERPT_CHARS]
            yield f"[{i}] {chunk.document_title}: {excerpt}\n\n"
