import { expect, type Page } from "@playwright/test";
import path from "node:path";

/**
 * Thin page objects for the DocSage demo stack.
 *
 * Every helper drives the real UI (no API shortcuts) and waits with
 * auto-retrying assertions robust to the app's 1.5s pipeline polling
 * cadence. Selectors are accessible names — see e2e/README.md for the
 * conventions.
 */

/** Password shared by every seeded demo account. */
export const DEMO_PASSWORD = "docsage-demo";

/** Seeded demo identities (see backend/src/docsage_api/seed.py). */
export const ADMIN_EMAIL = "admin@docsage.dev";
export const RILEY_EMAIL = "riley@docsage.dev";
export const MORGAN_EMAIL = "morgan@docsage.dev";
export const CASEY_EMAIL = "casey@docsage.dev";

/** Absolute path of the fixture corpus (regenerated by globalSetup). */
export const FIXTURES_DIR = path.join(__dirname, "..", "fixtures");

/** Approved library documents visible to every signed-in user. */
export const SEEDED_LIBRARY_TITLES = [
  "Telework and Remote Access Policy",
  "Information System Security Handbook",
  "FY2027 IT Budget",
  "Records Retention Schedule",
] as const;

/** Resolve a fixture file by name. */
export function fixture(name: string): string {
  return path.join(FIXTURES_DIR, name);
}

/** Collision-proof identity, safe across re-runs and parallel machines. */
export function uniqueEmail(prefix: string): string {
  return `qa-${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}@docsage.dev`;
}

/** Register through the /login form and land on /chat. */
export async function registerViaUi(
  page: Page,
  email: string,
  password: string = DEMO_PASSWORD,
  displayName = "QA Checker",
): Promise<void> {
  await page.goto("/login");
  await page.getByRole("tab", { name: "Register" }).click();
  await page.getByRole("textbox", { name: "Display name" }).fill(displayName);
  await page.getByRole("textbox", { name: "Email" }).fill(email);
  await page.getByRole("textbox", { name: "Password" }).fill(password);
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/chat$/, { timeout: 15_000 });
}

/** Sign in through the /login form and land on /chat. */
export async function loginViaUi(
  page: Page,
  email: string,
  password: string = DEMO_PASSWORD,
): Promise<void> {
  await page.goto("/login");
  await page.getByRole("textbox", { name: "Email" }).fill(email);
  await page.getByRole("textbox", { name: "Password" }).fill(password);
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/chat$/, { timeout: 15_000 });
}

/** Sign out through the user menu and land back on /login. */
export async function signOutViaUi(page: Page): Promise<void> {
  await page.getByRole("button", { name: "Open user menu" }).click();
  await page.getByRole("menuitem", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/login$/, { timeout: 15_000 });
}

/** Open the upload page and wait for the dropzone to be interactive. */
export async function openUpload(page: Page): Promise<void> {
  await page.goto("/upload");
  await expect(
    page.getByRole("button", { name: "Add files: drop documents here or press Enter to browse" }),
  ).toBeVisible();
}

export interface UploadOptions {
  /** Overrides the filename-derived default title. */
  title?: string;
  /** "library" is admin-only and requires a topic. */
  scope?: "personal" | "library";
  /** Library topic name (e.g. "Workplace Policy"). */
  topic?: string;
}

/**
 * Upload one fixture through the UI and wait for the ingestion pipeline to
 * finish. Returns the terminal status line, e.g. "Ready — 3 chunks indexed."
 * (library uploads append "· awaiting SME approval").
 */
export async function uploadAndWaitReady(
  page: Page,
  fileName: string,
  options: UploadOptions = {},
): Promise<string> {
  await openUpload(page);
  const input = page.locator('input[type="file"]');
  await input.setInputFiles(fixture(fileName));

  if (options.title) {
    await page.getByRole("textbox", { name: "Title" }).fill(options.title);
  }
  if (options.scope === "library") {
    // The radios are sr-only inputs inside labels, so click the visible
    // label text within the scope group (clicking the 1px input itself
    // never passes pointer-events hit-testing).
    const scopeGroup = page.getByRole("radiogroup", { name: "Scope" });
    await scopeGroup.getByText("Agency library", { exact: true }).click();
    const topicBox = page.getByRole("combobox", { name: "Library topic" });
    await topicBox.click();
    await page.getByRole("option", { name: options.topic ?? "Workplace Policy" }).click();
  }

  await page.getByRole("button", { name: /upload \d+ files?/i }).click();

  // The demo pipeline finishes in ~1-3s; the UI polls at 1.5s intervals, so
  // give the status line a generous budget. The demo banner is also a
  // role=status, hence the "chunks indexed" text filter.
  const status = page.getByRole("status").filter({ hasText: /chunks? indexed/ });
  await expect(status).toBeVisible({ timeout: 20_000 });
  if (options.scope === "library") {
    await expect(status).toContainText("awaiting SME approval");
  }
  return (await status.innerText()).trim();
}

export interface ChatAnswer {
  answerText: string;
  /** aria-labels of the citation chips, e.g. "Citation 1: press release". */
  citations: string[];
}

/**
 * Start a new conversation and wait until its (empty) transcript fetch has
 * settled before returning. Asking the very first question in a session the
 * instant it is created races the transcript fetch — if that response lands
 * after the answer stream, the page replaces the message list and the
 * streamed answer disappears (it is still persisted server-side). Settling
 * first keeps tests deterministic; the same thing happens when a human sees
 * the empty conversation before typing.
 */
export async function startConversation(
  page: Page,
  buttonName: "New conversation" | "Admin cross-search" = "New conversation",
): Promise<void> {
  const settled = page.waitForResponse(
    (response) =>
      response.url().includes("/api/chat/sessions/") &&
      response.url().endsWith("/messages") &&
      response.request().method() === "GET" &&
      response.status() === 200,
    { timeout: 10_000 },
  );
  await page.getByRole("button", { name: buttonName }).click();
  await settled;
}

/**
 * Type a question into the composer, send it with Enter, and wait for the
 * streamed answer to fully land (the streaming bubble is replaced by the
 * final message only after the SSE stream closes). The caller is responsible
 * for having a settled conversation selected — see startConversation.
 */
export async function askAndWait(
  page: Page,
  question: string,
  timeout = 30_000,
): Promise<ChatAnswer> {
  const log = page.getByRole("log", { name: "Messages" });
  // Assistant bubbles are identified by their "DocSage" byline paragraph.
  const bylines = log.locator("p").filter({ hasText: /^DocSage$/ });
  const before = await bylines.count();

  const composer = page.getByRole("textbox", { name: "Ask a question about your documents" });
  await composer.fill(question);
  await composer.press("Enter");

  await expect
    .poll(() => bylines.count(), { timeout, message: `assistant bubble should appear: ${question}` })
    .toBeGreaterThan(before);

  // Streaming is finished once the stop control is gone and the final bubble
  // has non-empty content. (Fast demo streams may complete before we even
  // sample; polling handles both orders.)
  const byline = bylines.nth(before);
  const content = byline.locator("xpath=following-sibling::div[1]");
  const stop = page.getByRole("button", { name: "Stop generating" });
  await expect
    .poll(async () => {
      if (await stop.isVisible().catch(() => false)) return "";
      return (await content.innerText()).trim();
    }, { timeout, message: `answer should finish streaming: ${question}` })
    .not.toBe("");

  const answerText = (await content.innerText()).trim();
  const chips = byline.locator("xpath=following-sibling::ul[1]").locator('[aria-label^="Citation"]');
  const citations = await chips.evaluateAll((elements) =>
    elements.map((element) => element.getAttribute("aria-label") ?? ""),
  );
  return { answerText, citations };
}
